// AUTO-GENERATED by parts_build/build_assets.py — do not hand-edit.
// fx/fy = part center as fraction of the outline image; fw/fh = size fractions.
const PARTS_POSITIONS = {
 "head": {
  "fx": 0.54404,
  "fy": 0.05279,
  "fw": 0.21483,
  "fh": 0.07285
 },
 "lefteye": {
  "fx": 0.49493,
  "fy": 0.09596,
  "fw": 0.09632,
  "fh": 0.0475
 },
 "righteye": {
  "fx": 0.59157,
  "fy": 0.09596,
  "fw": 0.1033,
  "fh": 0.0475
 },
 "mouth": {
  "fx": 0.54436,
  "fy": 0.13254,
  "fw": 0.14068,
  "fh": 0.04621
 },
 "neck": {
  "fx": 0.53105,
  "fy": 0.18068,
  "fw": 0.28897,
  "fh": 0.12837
 },
 "leftarm": {
  "fx": 0.25127,
  "fy": 0.30937,
  "fw": 0.31496,
  "fh": 0.2516
 },
 "lefthand": {
  "fx": 0.0865,
  "fy": 0.48524,
  "fw": 0.12738,
  "fh": 0.10334
 },
 "heart": {
  "fx": 0.532,
  "fy": 0.25321,
  "fw": 0.23131,
  "fh": 0.08986
 },
 "rightarm": {
  "fx": 0.78422,
  "fy": 0.31996,
  "fw": 0.27693,
  "fh": 0.27279
 },
 "righthand": {
  "fx": 0.90177,
  "fy": 0.50337,
  "fw": 0.15082,
  "fh": 0.10623
 },
 "stomach": {
  "fx": 0.5263,
  "fy": 0.31418,
  "fw": 0.35044,
  "fh": 0.16046
 },
 "crotch": {
  "fx": 0.51774,
  "fy": 0.43662,
  "fw": 0.37389,
  "fh": 0.14987
 },
 "leftleg": {
  "fx": 0.41572,
  "fy": 0.6741,
  "fw": 0.21546,
  "fh": 0.38479
 },
 "rightleg": {
  "fx": 0.61819,
  "fy": 0.69031,
  "fw": 0.19455,
  "fh": 0.37997
 },
 "feet": {
  "fx": 0.49683,
  "fy": 0.91752,
  "fw": 0.59189,
  "fh": 0.10591
 }
};
